@startuml
' left to right direction
skinparam packageStyle rectangle
actor "Anonymous User" as ausr
actor "Authenticated User" as usr
rectangle "WUI" {
    usecase "Change content" as change
    usecase "Manage files" as files
    usecase "Edit contents" as contents
    usecase "Create a revision" as commit
    usr --> change
    ausr --> change
    change ..> commit : <<include>>
    (Sign in) ..> change : <<extends>>
    files ..> change : <<extends>>
    contents ..> change : <<extends>>
}
rectangle "CLI" {
    ' usecase "SSH authentication" as sshauth
    usecase "Git remote access" as gitr
    usr --> gitr
    ' gitr ..> sshauth : <<include>>    
}
@enduml